inherit_from:
  - "https://www.goodcop.style/base.yml"

require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: single_quotes
